### ISSUE TITLE
TypeError when trying to use mockResponse

### ISSUE THREAD

**Issue by twilco** [knee-cola/jest-mock-axios#13]
Receiving this error when trying to use `axiosMock.mockResponse`.

```
TypeError: Cannot read property 'resolve' of undefined
    at Function.i.mockResponse (/Users/myusername/projects/theproject/frontend/node_modules/jest-mock-axios/dist/webpack:/lib/mock-axios.ts:104:26)
    at Object.<anonymous> (/Users/myusername/projects/theproject/frontend/api-sdk/__tests__/billing.test.js:17:15)
    at resolve (/Users/myusername/projects/theproject/frontend/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
    at Promise (<anonymous>)
    at mapper (/Users/myusername/projects/theproject/frontend/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
    at promise.then (/Users/myusername/projects/theproject/frontend/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Here's my test (**billing.test.js**):

```
import {
    getAllAccounts
} from '../billing'

import mockAxios from 'jest-mock-axios'

const headers = new Headers({
    'content-type': 'application/json'
})

beforeEach(() => {
    jest.resetAllMocks()
})

test('getAllAccounts', done => {
    let response = {
        data: [
            {
                id: 1
            }
        ]
    }
    
    mockAxios.mockResponse(response)
    const account = getAllAccounts().then(accounts => {
        expect(mockAxios.calls).toMatchSnapshot()
        expect(account).toEqual(undefined)
        done()
    })
})
```

I have created the __mocks__ folder.  My structure looks like this:

```
my_project
---- ...unrelated folders...
---- frontend
-------- __mocks__
------------ axios.js
-------- node_modules
-------- package.json
-------- api-sdk
------------ billing.js
------------ __tests__
---------------- __snapshots__
---------------- billing.test.js
```

**axios.js:**

```
import mockAxios from 'jest-mock-axios';
export default mockAxios;
```

**package.json:**

```
"devDependencies": {
    ...
    "jest": "^22.4.4",
    "jest-mock-axios": "^2.1.11",
    ...
  },
```

What am I doing wrong here?

**Comment by MatthewBooth** [comment]
Same issue. This library seems broken.

**Comment by kingjan1999** [comment]
Hi,

a bit late, but: You are using the library in the wrong way: As described in the README, your supposed to first trigger the request and then mock the response. So your code should be:

```js
const account = getAllAccounts().then(accounts => {
  expect(mockAxios.calls).toMatchSnapshot()
  expect(account).toEqual(undefined)
  done()
})
mockAxios.mockResponse(response)
```

**Comment by traviswimer** [comment]
@kingjan1999 Although what you said is correct in a sense, I would argue the library should be throwing a more meaningful message.

Also, this isn't just a problem of not reading the docs. For example, what if you change some code and the Axios request is no longer being made. Then your tests will fail with a confusing error, which is how you end up posting a comment on this issue. 😄

**Comment by kingjan1999** [comment]
You're totally right here @traviswimer and I think even though #26 already clarified the docs on this point, throwing a more meaningful error should be doable. I will look into this soon.
