### ISSUE TITLE
Setting defaults within production code causes TypeError during tests

### ISSUE THREAD

**Issue by dannyheard7** [knee-cola/jest-mock-axios#16]
Whenever defaults are set for axios in the code e.g. headers or baseUrl, when this code is tested using jest-mock-axios the following error is thrown:

`TypeError: Cannot read property 'headers' of undefined
at LoggedInContainer.setAuthHeader (src/App/Containers/LoggedInContainer.jsx:22:34)
      at new LoggedInContainer (src/App/Containers/LoggedInContainer.jsx:11:18)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:131:26)
      at Object.test (src/App/__tests__/Containers/LoggedInContainer.jsx:31:33)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by gkrinc** [comment]
There doesn't appear to be a `defaults` property. I suspect I'm doing something very similar to what you're doing @dannyheard7:

`client.defaults.headers.common['X-MY_AUTH-HEADER'] = 'header-value';`

I fixed this by extending the `mockAxios` object in `__mocks__/axios.js` like this:

```
import mockAxios from 'jest-mock-axios';

mockAxios.defaults = {
  headers: {
    common: [],
  },
}

export default mockAxios;
```

Hope that helps
