### ISSUE TITLE
unexpected token error

### ISSUE THREAD

**Issue by gquintard** [knee-cola/jest-mock-axios#68]
Hi,

Sorry for the newbie question, but I'm having trouble running the README example. I've created the three files as explained, i ran `npm i jest jest-mock-axios axios`, and then i'm hitting that wall:

```$ node_modules/.bin/jest
 FAIL  test/UppercaseProxy.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/gquintard/fun/jest/test/UppercaseProxy.spec.js:2
    import mockAxios from 'jest-mock-axios';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.483 s
Ran all test suites.
```

I tried `node --experimental-vm-modules node_modules/.bin/jest`, without success.

I'm sure the answer is obvious, but have little JS experience and I could really help a hand here

**Comment by kingjan1999** [comment]
Hi,

thank you for your interest in this lib and sorry for the long response time. This is not a problem of `jest-mock-axios` but rather a problem of your project structure. You are trying to use the `import` syntax in a project where it isn't supported. You may want to refer to the Jest documentation (e.g. the link mentioned already in the problem description, https://jestjs.io/docs/ecmascript-modules) to see how this can be solved.

I'm closing this for now, as this isn't related with `jest-mock-axios`

**Comment by gquintard** [comment]
Hi,

So, indeed, it seems it's common `npm` knowledge that I ignored until now. In case that can help someone in the future, I at least needed to:
- export NODE_OPTIONS=--experimental-vm-modules` 
- add `"type": "module"` to `package.json`
- add `import {jest} from '@jest/globals';` to the top of the `test/UppercaseProxy.spec.js` (I'm surprised this one isn't in the `README` though)

I'm now hitting another issue:

```
$ npm run test

> test
> jest

(node:167211) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  test/UppercaseProxy.spec.js
  ✕ UppercaseProxy should get data from the server and convert it to UPPERCASE (43 ms)

  ● UppercaseProxy should get data from the server and convert it to UPPERCASE

    expect(received).toHaveBeenCalledWith(...expected)

    Matcher error: received value must be a mock or spy function

    Received has value: undefined

      25 |     // b) went to the correct web service URL ('/web-service-url/')
      26 |     // c) if the payload was correct ('client is saying hello!')
    > 27 |     expect(mockAxios.post).toHaveBeenCalledWith('/web-service-url/', {data: clientMessage });
         |                            ^
      28 |
      29 |     // simulating a server response
      30 |     let responseObj = { data: 'server says hello!' };

      at Object.<anonymous> (test/UppercaseProxy.spec.js:27:28)

  ● UppercaseProxy should get data from the server and convert it to UPPERCASE

    TypeError: mockAxios.reset is not a function

       6 | afterEach(() => {
       7 |     // cleaning up the mess left behind the previous test
    >  8 |     mockAxios.reset();
         |               ^
       9 | });
      10 |
      11 | it('UppercaseProxy should get data from the server and convert it to UPPERCASE', () => {

      at Object.<anonymous> (test/UppercaseProxy.spec.js:8:15)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.95 s, estimated 1 s
Ran all test suites.
```

maybe it's still not a `jest-mock-axios` issue either, but i figured I'd ask
